version: "3.7"
services:
  rabbitmq:
    image: "rabbitmq:3.8.1-management"
    hostname: "rabbitmq"
    environment:
      # RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  rabbitmq:
  # - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
  #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
  #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
