version: "3.7"
services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: clew_medical
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # - db-data:/var/lib/postgresql/data
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:5.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: oran.bar.natan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
      PGDATA: /var/lib/pgadmin
    ports:
      - "8080:80"
    volumes:
      # - pgadmin-data:/var/lib/pgadmin
      - ./data/postgres:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
# volumes:
# db-data:
# pgadmin-data:
